repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
        exclude: tests/
      - id: destroyed-symlinks
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: tests/test_changes/
        files: \.(py|sh|rst|yml|yaml)$
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - '--autofix'
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        files: \.(py|sh|rst|yml|yaml)$
  - repo: 'https://github.com/psf/black'
    rev: 23.11.0
    hooks:
      - id: black
        exclude: tests/
  - repo: 'https://github.com/PyCQA/flake8'
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-blind-except
          - flake8-docstrings
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-docstrings
          - flake8-implicit-str-concat
          - pydocstyle>=5.0.0
        exclude: ^tests/test_cases/no_closing_bracket\.py$
  - repo: 'https://github.com/asottile/blacken-docs'
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==22.3.0
        exclude: ^.github/
  - repo: 'https://github.com/myint/rstcheck'
    rev: v6.2.0
    hooks:
      - id: rstcheck
        args:
          - '--report=warning'
  - repo: 'https://github.com/codespell-project/codespell'
    rev: v2.2.6
    hooks:
      - id: codespell
        files: \.(py|sh|rst|yml|yaml)$
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [ "--profile", "black", "--filter-files" ]
  - repo: 'https://github.com/myint/docformatter'
    rev: v1.7.5
    hooks:
      - id: docformatter
        args:
          - '--in-place'
